swagger: "2.0"
info:
  version: "1.0.0"
  title: "Shop API"
  contact:
    email: "apiteam@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "petstore.swagger.io"
basePath: "/v2"
paths:
  /shop: 
    get: 
      summary: "List shops" 
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        200:
          description: "Successful"
          schema: 
            $ref: "#/definitions/Shop"

    post: 
      summary: "Create shop"
      operationId: "addShop"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Shop object that needs to be added to the store"
        required: true
        schema:
          $ref: "#/definitions/Shop"
      responses:
        200:
          description: "Successful"
          schema: 
            $ref: "#/definitions/Shop"

    put: 
      summary: "Update shop"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        200:
          description: "Successful"
          schema: 
            $ref: "#/definitions/Shop/{id}"
            
    delete:
      summary: "Deletes a shop"
      description: ""
      operationId: "deleteShop"
      produces:
      - "application/json"
      parameters:
      - name: "shopId"
        in: "path"
        description: "Shop id to delete"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200: 
          description: "Deleted"
          schema:   
            $ref: "#/definitions/Shop/{id}"
        404:
          description: "Shop not found"
            
  /shop/getById:
    get: 
      summary: "List shops" 
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        200:
          description: "Successful"
          schema: 
            $ref: "#/definitions/Shop/{id}"


securityDefinitions:
  petstore_auth:
    type: "oauth2"
    authorizationUrl: "http://petstore.swagger.io/oauth/dialog"
    flow: "implicit"
    scopes:
      write:pets: "modify pets in your account"
      read:pets: "read your pets"
  api_key:
    type: "apiKey"
    name: "api_key"
    in: "header"
definitions:
  Shop: 
    type: "object"
    properties: 
      id: 
        type: "integer"
        format: "int64"
      name: 
        type: "string"
        example: "Zara"
      type: 
        type: "string"
        enum: 
          - "Shoe"
          - "Grocery"
      location: 
        type: "object"
        properties:
          postcode: 
            type: "string"
            example: "SP10 1DE"
          town: 
            type: "string"
            example: "Andover"
  
        
  ApiResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      type:
        type: "string"
      message:
        type: "string"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"